insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Grilled Chicken Salad', 300, '25g', '10g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Grilled Chicken Salad', 300, '25g', '10g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Vegetable Omelette', 250, '18g', '10g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Tofu and Vegetable Stir Fry', 400, '20g', '40g', '15g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Baked Salmon with Sweet Potatoes', 450, '30g', '30g', '25g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Spinach and Feta Stuffed Chicken', 400, '35g', '10g', '20g', '35 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Black Bean and Corn Quesadilla', 350, '15g', '35g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Beef and Broccoli', 500, '35g', '25g', '30g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Pesto Pasta with Cherry Tomatoes', 400, '15g', '50g', '20g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Grilled Pork Chops with Roasted Vegetables', 450, '30g', '20g', '30g', '40 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Quinoa and Black Bean Bowl', 350, '15g', '40g', '10g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Lentil Soup with Kale', 300, '20g', '30g', '10g', '45 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Pulled Pork Sandwich', 500, '25g', '40g', '20g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Sweet and Sour Chicken', 450, '30g', '25g', '25g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Roasted Vegetable Salad', 300, '10g', '20g', '25g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Mediterranean Chicken and Couscous', 400, '30g', '30g', '15g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Shrimp and Avocado Salad', 350, '20g', '15g', '25g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Grilled Steak with Chimichurri Sauce', 450, '30g', '10g', '30g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Eggplant Parmesan', 400, '20g', '35g', '15g', '45 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Honey Mustard Glazed Salmon', 350, '25g', '10g', '25g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Chickpea and Sweet Potato Curry', 400, '15g', '45g', '15g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Stuffed Bell Peppers', 350, '20g', '30g', '10g', '45 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Lemon Garlic Shrimp and Asparagus', 300, '25g', '10g', '20g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Baked Cod with Roasted Vegetables', 400, '30g', '20g', '20g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Sesame Ginger Tofu with Rice Noodles', 350, '20g', '35g', '10g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Beef Stroganoff', 450, '25g', '30g', '20g', '40 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Stuffed Zucchini Boats', 350, '15g', '25g', '20g', '35 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Greek Turkey Burgers', 400, '25g', '20g', '25g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Grilled Shrimp Skewers with Vegetables', 350, '25g', '15g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Dinner','Sesame-Ginger Beef Stir Fry', 450, '35g', '20g', '25g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Grilled Chicken Sandwich with Avocado', 400, '30g', '30g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Turkey and Hummus Wrap', 350, '20g', '40g', '10g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Caprese Salad with Balsamic Glaze', 300, '15g', '15g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Tuna Salad Lettuce Wraps', 250, '20g', '10g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Greek Yogurt and Fruit Parfait', 200, '10g', '30g', '5g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Black Bean and Sweet Potato Salad', 350, '15g', '40g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Roasted Vegetable and Quinoa Salad', 300, '10g', '30g', '15g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Chicken Caesar Wrap', 400, '25g', '30g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Broccoli Cheddar Soup', 350, '15g', '25g', '20g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Veggie and Hummus Sandwich', 300, '15g', '40g', '10g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Sushi Rolls', 400, '20g', '60g', '5g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Mediterranean Chicken Wrap', 350, '25g', '30g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Greek Salad with Grilled Chicken', 350, '30g', '15g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Soba Noodle Salad with Tofu', 300, '20g', '30g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Turkey and Cheese Sandwich', 400, '25g', '30g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Salmon and Avocado Toast', 350, '20g', '30g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Spinach and Mushroom Omelette', 250, '15g', '10g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Veggie Burger with Sweet Potato Fries', 450, '20g', '40g', '20g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Taco Salad with Ground Beef', 400, '25g', '20g', '25g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Quinoa Salad with Chicken and Vegetables', 350, '30g', '20g', '15g', '25 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Caprese Sandwich with Tomato Soup', 500, '20g', '50g', '20g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Falafel Pita with Tzatziki Sauce', 350, '15g', '30g', '10g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Chicken Caesar Wrap', 400, '25g', '25g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Shrimp and Vegetable Stir Fry', 350, '20g', '25g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Caprese Salad', 250, '10g', '10g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Avocado Toast with Smoked Salmon', 300, '20g', '20g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Turkey and Swiss Sandwich', 350, '25g', '30g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Roasted Vegetable Wrap', 300, '10g', '30g', '10g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Shrimp and Vegetable Stir Fry', 400, '20g', '30g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Lunch','Southwestern Quinoa Salad', 350, '15g', '30g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Greek Yogurt Parfait with Berries and Granola', 300, '20g', '40g', '10g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Avocado Toast with Poached Egg', 350, '15g', '30g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Oatmeal with Banana and Peanut Butter', 400, '15g', '50g', '10g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Egg and Cheese Sandwich', 450, '20g', '30g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Smoothie Bowl with Mixed Berries and Almond Milk', 300, '10g', '50g', '5g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Breakfast Burrito with Sausage, Eggs, and Cheese', 500, '25g', '30g', '25g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Baked Oatmeal with Blueberries and Almonds', 350, '10g', '40g', '15g', '30 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Bagel with Cream Cheese and Smoked Salmon', 400, '20g', '30g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Pancakes with Fresh Fruit and Maple Syrup', 450, '10g', '60g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Breakfast Quinoa with Cinnamon and Almonds', 300, '10g', '40g', '10g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Egg and Veggie Scramble', 350, '20g', '15g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','French Toast with Berries and Whipped Cream', 400, '15g', '40g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Avocado Toast with Eggs', 350, '18g', '28g', '20g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Greek Yogurt with Berries and Granola', 250, '15g', '30g', '5g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Spinach and Feta Omelette', 300, '20g', '5g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Healthy Breakfast Burrito', 400, '20g', '35g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Pancakes with Blueberries and Maple Syrup', 350, '8g', '50g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Egg and Cheese Sandwich', 300, '15g', '25g', '10g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Fruit and Yogurt Smoothie Bowl', 250, '10g', '35g', '5g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Bacon and Egg Breakfast Wrap', 400, '20g', '30g', '15g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Cinnamon French Toast with Bananas', 350, '8g', '40g', '10g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Green Smoothie', 200, '5g', '30g', '10g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Egg and Vegetable Scramble', 300, '15g', '10g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Bagel with Cream Cheese and Smoked Salmon', 400, '20g', '30g', '15g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Greek Yogurt with Berries and Granola', 300, '20g', '30g', '10g', '5 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Huevos Rancheros', 400, '25g', '30g', '15g', '20 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Banana Oat Pancakes', 350, '15g', '45g', '10g', '15 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Smoked Salmon Bagel with Cream Cheese', 450, '25g', '35g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Avocado Toast with Poached Eggs', 400, '20g', '30g', '20g', '10 mins');
insert into meals (mealType, mealName, calories, gramsProtein, gramsCarbs, gramsFat, timeToCook) values ('Breakfast','Blueberry Chia Seed Pudding', 250, '10g', '30g', '10g', '5 mins');
